name: ybuild2

on:
  workflow_dispatch:
  repository_dispatch: # 允许通过 API 触发

jobs:
  ybuild2:
    runs-on: windows-latest
    name: Build Yim v2 and Golt
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
            fetch-depth: 1

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup .Net6.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      - name: Setup Nuget
        uses: nuget/setup-nuget@v2

      - name: Download and Install CMake 4.0.2 (Windows)
        shell: powershell
        run: |
          # 下载 CMake 4.0.2 for Windows x64
          $cmakeUrl = "https://github.com/Kitware/CMake/releases/download/v4.0.2/cmake-4.0.2-windows-x86_64.zip"
          $downloadPath = "$env:RUNNER_TEMP\cmake-4.0.2.zip"
          curl.exe -L -o $downloadPath $cmakeUrl
    
          # 解压到 C:\cmake-4.0.2
          Expand-Archive -Path $downloadPath -DestinationPath "C:\"
          Rename-Item -Path "C:\cmake-4.0.2-windows-x86_64" -NewName "C:\cmake-4.0.2"
    
          # 添加到 PATH（仅当前 Job 生效）
          $cmakePath = "C:\cmake-4.0.2\bin"
          echo "Adding CMake to PATH: $cmakePath"
          echo "$cmakePath" >> $env:GITHUB_PATH
    
      - name: Verify CMake version
        run: cmake --version
      
      - name: Check CMake version
        run: cmake --version
        
      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          
      - name: download YimMenuV2 Sources
        run: |
          Invoke-WebRequest -Uri https://antfcc0.1007890.xyz/download_yimv2src -OutFile yimmenuv2.zip
          Expand-Archive -Path yimmenuv2.zip -DestinationPath ./
          
      - name: Checkout golt Sources
        uses: actions/checkout@v4
        with:
          repository: sch-lda/GTA5OnlineTools
          path: GTA5OnlineTools
          fetch-depth: 1


      - name: Generate YimmenuV2 CMake project
        run: cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=RelWithDebInfo -S./yimmenuv2 -Bbuildv2 -G Ninja

      - name: Build YimmenuV2 64bit release DLL
        run: cmake --build ./buildv2 --config RelWithDebInfo --target YimMenuV2 --
          
      - name: Upload V2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: yimv2dll
          path: buildv2/YimMenuV2.dll

      - name: ready for build golt
        run: |
             mkdir GTA5OnlineTools/GTA5OnlineTools/Properties/PublishProfiles
             rm GTA5OnlineTools/GTA5Shared/Files/YimMenu/NewBase.dll
             cp buildv2/YimMenuV2.dll GTA5OnlineTools/GTA5Shared/Files/YimMenu/NewBase.dll
             Invoke-WebRequest -Uri https://github.com/sch-lda/yctest2/releases/download/CI/YimMenu.dll  -OutFile YimMenu.dll
             cp YimMenu.dll GTA5OnlineTools/GTA5Shared/Files/YimMenu/YimMenu.dll
             cp CIprop/FolderProfile.pubxml GTA5OnlineTools/GTA5OnlineTools/Properties/PublishProfiles/FolderProfile.pubxml
             cd GTA5OnlineTools/
             dotnet publish /p:Configuration=Release /p:PublishProfile=FolderProfile
             cd ..
             ./CIprop/t3ll2.exe ${{ secrets.ARG_V1 }}
             cp CIprop/test2_boxed.exe GTA5OnlineTools/GTA5OnlineTools/bin/x64/Release/net6.0-windows/publish/win-x64/
             cd GTA5OnlineTools/GTA5OnlineTools/bin/x64/Release/net6.0-windows/publish/win-x64/
             ./test2_boxed.exe ${{ secrets.ARG_V1 }}

      - name: Upload GTA5OnlineTools-CI
        uses: actions/upload-artifact@v4
        with:
          name: GTA5OnlineTools
          path: GTA5OnlineTools/GTA5OnlineTools/bin/x64/Release/net6.0-windows/publish/win-x64/GTA5OnlineTools.exe
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: CI
          tag_name: CI
          body: |
            **由于小助手已停止更新，自动构建程序将仅同步yimmenu v2**
          files: |
            GTA5OnlineTools/GTA5OnlineTools/bin/x64/Release/net6.0-windows/publish/win-x64/GTA5OnlineTools.exe
            buildv2/YimMenuV2.dll
            
      - name: ready for build golt with runtime
        run: |

             cp CIprop/FolderProfile-withruntime.pubxml GTA5OnlineTools/GTA5OnlineTools/Properties/PublishProfiles/FolderProfile.pubxml
             cd GTA5OnlineTools/
             dotnet publish /p:Configuration=Release /p:PublishProfile=FolderProfile
             cd ..
             cp CIprop/test2_boxed.exe GTA5OnlineTools/GTA5OnlineTools/bin/x64/Release/net6.0-windows/publish/win-x64/
             cd GTA5OnlineTools/GTA5OnlineTools/bin/x64/Release/net6.0-windows/publish/win-x64/
             rm test2_boxed.exe

      - name: Upload GTA5OnlineTools-CI-with-runtime
        uses: actions/upload-artifact@v4
        with:
          name: GTA5OnlineTools_runtime
          path: GTA5OnlineTools/GTA5OnlineTools/bin/x64/Release/net6.0-windows/publish/win-x64/
